[package]
name = "menstruation-rs"
version = "0.1.0"
authors = ["Kierán Meinhardt <kieran.meinhardt@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.5"
scraper = "0.9.0"
term-painter = "0.2.4"
