[package]
name = "menstruation-rs"
version = "0.1.0"
authors = ["Kierán Meinhardt <kieran.meinhardt@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1"
reqwest = "0.9.5"
scraper = "0.9.0"
ansi_term = "0.11.0"
chrono = "0.4.6"
